import = [ "~/dotfiles/alacritty/themes/gruvbox-material.toml" ]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[font]
size = 14.0

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Monospace"

[window]
opacity = 0.9
decorations = "None"

[window.padding]
x = 10
y = 10
